name: CI & SonarQube
on:
  pull_request:
    branches: ["main", "develop", "release"]
    types: [opened, synchronize, reopened]
  push:
    branches: ["main", "develop", "release"]

env:
  FLAVOR: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  # ------------------------------------------------------
  # JOB 1: Análisis con SonarQube / SonarCloud 🦉
  # ------------------------------------------------------
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código 🚚
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Desactivar shallow clone para un mejor análisis de Sonar

      - name: Configurar Java ☕
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Configurar Flutter 💙
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Instalar dependencias 📦
        run: flutter pub get

      - name: Crear archivo .env 📝
        run: |
          if [ "${{ env.FLAVOR }}" = "prod" ]; then
            echo "${{ secrets.ENV_PROD }}" > .env.prod
            echo "GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID_PROD }}" >> .env.prod
          else
            echo "${{ secrets.ENV_DEV }}" > .env.dev
            echo "GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID_DEV }}" >> .env.dev
          fi
          touch .env.dev
          touch .env.prod

      - name: Ejecutar pruebas y generar cobertura 🧪
        run: flutter test --coverage --flavor ${{ env.FLAVOR }}

      - name: SonarQube Scan 🔍
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}